
baseURL= "https://sbueringer.github.io/kubecon-slides"
languageCode = "en-us"
title = "KubeCon Slides"
theme = "meghna-hugo"
# Google Analytics
googleAnalytics = "UA-119567122-2"

custom_css = ["css/custom.css"]

[privacy]
  [privacy.googleAnalytics]
    anonymizeIP = true
    disable = false
    respectDoNotTrack = true
    useSessionStorage = true


# Menu
[menu]

# Site params
[params]
home= "Overview"
logo = "images/logo.png"
# Meta data
description = "Airspace Hugo theme"
author = "Themefisher"

# footer
[params.footer]
    copyright = "Themefisher Team"
    copyrightURL = "http://www.themefisher.com"

    [[params.footer.socialIcon]]
    icon = "tf-ion-social-twitter"
    url = "https://twitter.com/sbueringer"

    [[params.footer.socialIcon]]
    icon = "tf-ion-social-github"
    url = "https://github.com/sbueringer"

    [[params.footer.socialIcon]]
    icon = "tf-ion-social-facebook"
    url = "https://www.facebook.com/stefan.buringer"

    [[params.footer.socialIcon]]
    icon = "tf-ion-social-linkedin"
    url = "https://www.linkedin.com/in/stefan-b%C3%BCringer-a1b33258"
